image: Visual Studio 2017

version: 1.6.3.{build}

branches:
    only:
        - master

clone_depth: 1

# scripts that run after cloning repository
install:
    - set PATH=C:\Go\bin;%PATH%
    - set GO111MODULE=on

# scripts that run before build
before_build:
    - go env
    - go version

# custom build scripts
build_script:
    - go build
    - cd webui && go build -o getnovel-webui.exe
    - cd ..

# scripts that run after build
after_build:
    - mkdir distrib\getnovel-windows-amd64\webui\templates distrib\getnovel-windows-amd64\config distrib\getnovel-windows-amd64\preset distrib\getnovel-windows-amd64\webui
    - copy "%APPVEYOR_BUILD_FOLDER%\preset\*.*" "distrib\getnovel-windows-amd64\preset\"
    - copy "%APPVEYOR_BUILD_FOLDER%\config\*.*" "distrib\getnovel-windows-amd64\config\"
    - copy "%APPVEYOR_BUILD_FOLDER%\webui\templates\*.*" "distrib\getnovel-windows-amd64\webui\templates\"
    - copy "%APPVEYOR_BUILD_FOLDER%\webui\getnovel-webui.exe" "distrib\getnovel-windows-amd64\webui\"
    - copy "%APPVEYOR_BUILD_FOLDER%\getnovel.exe" "distrib\getnovel-windows-amd64\getnovel.exe"
    - cd distrib
    - 7z a getnovel-windows-amd64.zip getnovel-windows-amd64

artifacts:
    - path: distrib\getnovel-windows-amd64.zip
      name: portable
    - path: distrib\getnovel-windows-amd64\getnovel.exe
      name: exe_only
