image: Visual Studio 2017

version: 1.6.3.{build}

branches:
    only:
        - master

environment:
    matrix:
        - GOOS: windows
          GOARCH: amd64
          PREFIX: windows-amd64
          SUFFIX: .exe
        - GOOS: darwin
          GOARCH: amd64
          PREFIX: darwin-amd64
          SUFFIX: 

clone_depth: 1

# scripts that run after cloning repository
install:
    - set PATH=C:\Go\bin;%PATH%
    - set GO111MODULE=on

# scripts that run before build
before_build:
    - go env
    - go version

# custom build scripts
build_script:
    - go build -ldflags="-s -w -X main.sha1ver=`git rev-parse HEAD` -X main.buildTime=$(date +'%Y-%m-%d_%T')" -o getnovel-%PREFIX%%SUFFIX%
    - cd webui && go build -ldflags="-s -w -X main.sha1ver=`git rev-parse HEAD` -X main.buildTime=$(date +'%Y-%m-%d_%T')" -o getnovel-webui%PREFIX%%SUFFIX%
    - cd ..

# scripts that run after build
after_build:
    - mkdir distrib\getnovel-%PREFIX%\webui\templates distrib\getnovel-%PREFIX%\config distrib\getnovel-%PREFIX%\preset
    - copy "%APPVEYOR_BUILD_FOLDER%\preset\*.*" "distrib\getnovel-%PREFIX%\preset\"
    - copy "%APPVEYOR_BUILD_FOLDER%\config\*.*" "distrib\getnovel-%PREFIX%\config\"
    - copy "%APPVEYOR_BUILD_FOLDER%\webui\templates\*.*" "distrib\getnovel-%PREFIX%\webui\templates\"
    - copy "%APPVEYOR_BUILD_FOLDER%\webui\getnovel-%PREFIX%%SUFFIX%" "distrib\getnovel-%PREFIX%\webui\"
    - copy "%APPVEYOR_BUILD_FOLDER%\getnovel-%PREFIX%%SUFFIX%" "distrib\getnovel-%PREFIX%\getnovel%SUFFIX%"
    - cd distrib
    - 7z a getnovel-%PREFIX%.zip getnovel-%PREFIX%

artifacts:
    - path: distrib\getnovel-%PREFIX%.zip
      name: portable
    - path: distrib\getnovel-%PREFIX%\getnovel-%PREFIX%%SUFFIX%
      name: exe_only
